# Generated by Django 3.2.7 on 2023-11-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('año', models.CharField(max_length=4)),
                ('dias', models.CharField(max_length=2)),
                ('calificacion', models.CharField(max_length=1)),
            ],
        ),
    ]
